akka/akka-sdk

.github/workflows/publish.yml

Brings back Enno's PR(#6) that I smashed.

chore: adapt secret name

---

docs/README.md
docs/src/modules/ROOT/pages/index.adoc
docs/src/modules/java/pages/author-your-first-service.adoc

Brings back Enno's PR(#7) that I smashed.

docs: less detail in Hello World

---

.github/workflows/docs-cli-updates.yml

chore: syntax in CLI version workflow

---

docs/src/modules/reference/pages/release-notes.adoc

docs: CLI 3.0.6

---

updateRuntimeVersions.sh

Making it easier to update runtime version.

chore: pass runtime version as arg

---

LICENSE
akka-javasdk-maven/akka-javasdk-archetype/pom.xml
akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk-maven/pom.xml
samples/choreography-saga-quickstart/pom.xml
samples/doc-snippets/pom.xml
samples/endpoint-jwt/pom.xml
samples/event-sourced-counter-brokers/pom.xml
samples/event-sourced-customer-registry-subscriber/pom.xml
samples/event-sourced-customer-registry/pom.xml
samples/key-value-counter/pom.xml
samples/key-value-customer-registry/pom.xml
samples/key-value-shopping-cart/pom.xml
samples/reliable-timers/pom.xml
samples/shopping-cart-quickstart/pom.xml
samples/spring-dependency-injection/pom.xml
samples/tracing/pom.xml
samples/transfer-workflow-compensation/pom.xml
samples/transfer-workflow/pom.xml
samples/view-store/pom.xml

chore: Update change date for 3.0.1

---

akka-javasdk-tests/src/test/java/akkajavasdk/EventSourcedEntityTest.java
akka-javasdk-tests/src/test/resources/application.conf
akka-javasdk-tests/src/test/resources/logback-test.xml
akka-javasdk/src/main/scala/akka/javasdk/impl/JsonMessageCodec.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/Settings.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/ReflectiveEventSourcedEntityRouter.scala

* test that verifies snapshots
* pass snapshotEvery in SpiSettings
* use entityStateType when deserializing state (snapshot)
On top of https://github.com/akka/akka-sdk/pull/47

chore: Snapshots and StateSerializer type

---

docs/src/modules/operations/pages/projects/container-registries.adoc
docs/src/modules/support/nav.adoc
docs/src/modules/support/pages/community-forum.adoc
docs/src/modules/support/pages/email.adoc
docs/src/modules/support/pages/frequently-asked-questions.adoc
docs/src/modules/support/pages/paid-plans.adoc
docs/src/modules/support/pages/request-a-demo.adoc
docs/src/modules/support/pages/troubleshooting.adoc

Pages where missing in nav. 
Update Contact Us URLs.

docs: review support pages

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/ReflectiveWorkflowRouter.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala
project/Dependencies.scala

chore: new workflow spi adt

---

akka-javasdk/src/main/java/akka/javasdk/http/RequestContext.java
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
docs/src/modules/java/pages/http-endpoints.adoc

chore: endpoint request header follow up and docs

---

docs/src/modules/java/pages/author-your-first-service.adoc

Closes: lightbend/kalix-docs#2253

fix(docs): clarify IntelliJ setup instructions

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/client/EntityClientImpl.scala
akka-javasdk/src/test/java/akka/javasdk/client/ComponentClientTest.java
project/Dependencies.scala

Downstream depending on release of https://github.com/lightbend/kalix-runtime/pull/3309

chore: More evolvable SpiComponents

---

docs/src/modules/concepts/pages/declarative-effects.adoc

docs: declarative effects title style

---

akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/api/package-info.java
akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/application/package-info.java
akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/domain/package-info.java

As a convenient nudge in the right direction for structuring packages when starting from the archetype.

chore: Default domain and application packages in archetype

---

akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/application/package-info.java

chore: Wrong package name in #140

---

akka-javasdk-tests/src/test/java/akkajavasdk/ViewIntegrationTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/views/AllTheTypesKvEntity.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/views/AllTheTypesView.java
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewSchema.scala
docs/src/modules/java/partials/query-syntax-reference.adoc

References https://github.com/lightbend/kalix-runtime/issues/3313
(But only a partial fix)

feat: Support ZonedDateTime in views

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/main/scala/akka/javasdk/impl/AclDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/GrpcEndpointDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/HttpEndpointDescriptorFactory.scala
project/Dependencies.scala
samples/doc-snippets/src/main/java/com/example/api/ExampleGrpcEndpointImpl.java
samples/event-sourced-customer-registry/src/main/java/customer/api/CustomerGrpcEndpointImpl.java

Refs https://github.com/lightbend/kalix-runtime/issues/3348
This is an early version just if we want to release early. Lacking test coverage and probably some refactoring as well.

feat: support for ACLs in grpc endpoints

---

docs/src/modules/reference/pages/cli/installation.adoc

Especially Linux users want to do it manually.

docs: show CLI download URL

---

docs/src/modules/java/partials/query-syntax-advanced.adoc

Got broken in #118 but we somehow did not notice until now.

docs: Fix advanced query snippet references

---

akka-javasdk-tests/src/test/java/akkajavasdk/GrpcEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestGrpcServiceImpl.java
akka-javasdk-tests/src/test/protobuf/akkajavasdk/test_grpc_service.proto
akka-javasdk-tests/src/test/resources/application.conf
akka-javasdk/src/main/resources/reference.conf
akka-javasdk/src/main/scala/akka/javasdk/impl/grpc/GrpcClientProviderImpl.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/grpc/GrpcProviderClientImplSpec.scala
docs/src/modules/java/pages/component-and-service-calls.adoc
samples/doc-snippets/src/main/resources/application.conf

References https://github.com/lightbend/kalix-runtime/issues/3347

chore: gRPC clients config sanitization and allow service override in dev

---

LICENSE

References https://github.com/akka/akka-sdk/issues/181

chore: Update LICENSE for release 3.1.0

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/TestKit.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/TestKitSupport.java
akka-javasdk-tests/src/test/java/akkajavasdk/GrpcEndpointTest.java
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/grpc/GrpcClientProviderImpl.scala
docs/src/modules/java/pages/grpc-endpoints.adoc
samples/doc-snippets/src/test/java/com/example/api/ExampleGrpcEndpointTest.java

References https://github.com/lightbend/kalix-runtime/issues/3351
Mostly done but needs docs

feat: gRPC endpoint clients provided by testkit

---

akka-javasdk-tests/src/test/java/akkajavasdk/GrpcEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestGrpcServiceImpl.java
akka-javasdk-tests/src/test/protobuf/akkajavasdk/test_grpc_service.proto
akka-javasdk/src/main/java/akka/javasdk/annotations/Acl.java

Close https://github.com/lightbend/kalix-runtime/issues/3403

test: ACL deny code inheritance

---

akka-javasdk/src/main/scala/akka/javasdk/impl/GrpcEndpointDescriptorFactory.scala

I just learned about this. I thought it didn't exist. :)

chore: use capitalize from std lib

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
project/Dependencies.scala
project/plugins.sbt

References https://github.com/lightbend/kalix-runtime/issues/3429

bump: Runtime 1.3.4

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/keyvalueentities/user/UserEntity.java
akka-javasdk/src/main/java/akka/javasdk/keyvalueentity/KeyValueEntity.java
akka-javasdk/src/main/scala/akka/javasdk/impl/ComponentDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/keyvalueentity/KeyValueEntityEffectImpl.scala
samples/choreography-saga-quickstart/src/main/java/user/registry/application/UniqueEmailEntity.java
samples/event-sourced-customer-registry/src/main/java/customer/application/CustomerEntity.java
samples/key-value-counter/src/main/java/com/example/application/CounterEntity.java
samples/key-value-customer-registry/src/main/java/customer/application/CustomerEntity.java
samples/key-value-shopping-cart/src/main/java/com/example/application/ShoppingCartEntity.java
samples/reliable-timers/src/main/java/com/example/application/OrderEntity.java
samples/view-store/src/main/java/store/order/application/OrderEntity.java

merging after releasing the runtime

feat: ReadOnlyEffect for KVE

---

docs/src/modules/java/pages/shopping-cart-quickstart.adoc

Add numbered steps to improve readability and consistency with other sections.
Before
After

docs(quickstart) add numbering to actionable steps

---

akka-javasdk/src/main/java/akka/javasdk/http/HttpResponses.java
docs/src/modules/java/pages/http-endpoints.adoc
samples/doc-snippets/src/main/java/com/example/acl/PaymentEndpoint.java
samples/doc-snippets/src/main/java/com/example/api/ExampleEndpoint.java
samples/doc-snippets/src/main/java/com/example/callanotherservice/DelegatingServiceEndpoint.java
samples/doc-snippets/src/main/java/com/example/jwt/HelloJwtEndpoint.java
samples/key-value-customer-registry/README.md
samples/key-value-customer-registry/src/main/java/customer/api/CustomerEndpoint.java

References https://github.com/lightbend/kalix-runtime/issues/3094
Not sure if we should have some reference docs, or if it is enough of discoverability with the static factory since it is a power user kid of feature.

feat: API for Server Sent Events (SSE) streaming from HTTP endpoint

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk-tests/src/test/java/akkajavasdk/GrpcEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestGrpcServiceImpl.java
akka-javasdk-tests/src/test/protobuf/akkajavasdk/test_grpc_service.proto
akka-javasdk/src/main/java/akka/javasdk/grpc/AbstractGrpcEndpoint.java
akka-javasdk/src/main/java/akka/javasdk/grpc/GrpcRequestContext.java
akka-javasdk/src/main/scala/akka/javasdk/impl/GrpcEndpointDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
project/Dependencies.scala

Refs https://github.com/lightbend/kalix-runtime/issues/3473
Depends on runtime release.

feat: API to access to grpc metadata

---

docs/src/modules/reference/pages/release-notes.adoc

- https://github.com/akka/homebrew-brew/commit/aa70779d81e0f256589132c1ee39a4bd8b240b22

docs: Akka CLI 3.0.12

---

docs/src/modules/java/pages/access-control.adoc

Close https://github.com/lightbend/kalix/issues/12366
Change this:
To this:
Also, adds a note about disabling ACLs for IT specifically.

docs: disabling ACLs for integration tests

---

docs/src/modules/java/pages/grpc-endpoints.adoc

docs: fix code references for example

---

docs/src/modules/java/pages/grpc-endpoints.adoc
docs/src/modules/java/pages/views.adoc

docs: fix streaming the result cross link

---

project/SamplesCompilationProject.scala
samples/spring-dependency-injection/pom.xml

Some CVE out for the old version

bump: Spring 6.2.3 in sample

---

docs/src/modules/java/pages/http-endpoints.adoc
docs/src/modules/reference/pages/release-notes.adoc

References
- https://github.com/akka/akka-sdk/releases/tag/v3.2.0

docs: explaining 3.2.0 release notes

---

docs/src/modules/java/pages/component-and-service-calls.adoc
samples/event-sourced-counter-brokers/src/main/java/counter/api/CounterEndpoint.java
samples/shopping-cart-quickstart/src/main/java/shoppingcart/api/ShoppingCartEndpoint.java

docs: fixing component client docs

---

.github/workflows/update-sdk-version.yml
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewDescriptorFactory.scala
docs/src/modules/java/pages/component-and-service-calls.adoc
docs/src/modules/java/pages/http-endpoints.adoc
docs/src/modules/java/pages/samples.adoc
docs/src/modules/reference/pages/release-notes.adoc
project/SamplesCompilationProject.scala
samples/event-sourced-counter-brokers/src/main/java/counter/api/CounterEndpoint.java
samples/shopping-cart-quickstart/src/main/java/shoppingcart/api/ShoppingCartEndpoint.java
samples/spring-dependency-injection/pom.xml

Release docs

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/TestKit.java

* there was a confusing 20 seconds timeout

fix: Fail TestKit startup immediately if runtime validations fail

---

docs/src/modules/operations/pages/projects/broker-aiven.adoc
docs/src/modules/support/pages/frequently-asked-questions.adoc
docs/src/modules/support/pages/troubleshooting.adoc

docs: update support email

---

samples/key-value-shopping-cart/src/main/java/com/example/api/ShoppingCartDTO.java
samples/key-value-shopping-cart/src/main/java/com/example/api/ShoppingCartEndpoint.java
samples/key-value-shopping-cart/src/main/java/com/example/application/ShoppingCartEntity.java
samples/key-value-shopping-cart/src/main/java/com/example/domain/ShoppingCart.java
samples/key-value-shopping-cart/src/test/java/com/example/ShoppingCartIntegrationTest.java

* We are not using DTOs anywhere else between endpoint and entity

chore: Cleanup key-value-shopping-cart sample

---

LICENSE

Refs https://github.com/akka/akka-sdk/issues/284

chore: Update LICENSE ahead of v3.2.1

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EventingTestKit.java
akka-javasdk/src/main/java/akka/javasdk/CloudEvent.java
akka-javasdk/src/main/scala/akka/javasdk/impl/MetadataImpl.scala
docs/src/modules/java/pages/dev-best-practices.adoc
docs/src/modules/java/pages/views.adoc
docs/styles/config/vocabularies/Akka/accept.txt
samples/doc-snippets/src/main/java/com/example/application/MyConsumer.java
samples/event-sourced-counter-brokers/src/main/java/counter/CounterSetup.java
samples/event-sourced-counter-brokers/src/main/java/counter/api/CounterEndpoint.java
samples/event-sourced-counter-brokers/src/main/java/counter/application/CounterByValueView.java
samples/event-sourced-counter-brokers/src/main/java/counter/application/CounterByValueViewEnrichment.java
samples/event-sourced-counter-brokers/src/main/java/counter/application/CounterEntity.java
samples/event-sourced-counter-brokers/src/main/java/counter/application/CounterStore.java
samples/event-sourced-counter-brokers/src/main/java/counter/application/CounterStoreUpdater.java
samples/event-sourced-counter-brokers/src/main/java/counter/domain/CounterEvent.java
samples/event-sourced-counter-brokers/src/test/java/counter/application/CounterByValueViewTest.java
samples/event-sourced-counter-brokers/src/test/java/counter/application/CounterIntegrationTest.java
samples/event-sourced-counter-brokers/src/test/java/counter/application/CounterStoreUpdaterTest.java
samples/event-sourced-customer-registry/src/main/java/customer/CustomerRegistrySetup.java
samples/event-sourced-customer-registry/src/main/java/customer/application/CustomerByEmailView.java
samples/event-sourced-customer-registry/src/main/java/customer/application/CustomerStore.java
samples/event-sourced-customer-registry/src/main/java/customer/application/CustomerStoreUpdater.java
samples/event-sourced-customer-registry/src/test/java/customer/application/CustomerStoreUpdaterTest.java
samples/transfer-workflow-compensation/src/main/java/com/example/wallet/application/WalletEntity.java
samples/transfer-workflow-compensation/src/main/java/com/example/wallet/domain/Wallet.java
samples/transfer-workflow-compensation/src/main/java/com/example/wallet/domain/WalletCommand.java
samples/transfer-workflow-compensation/src/test/java/com/example/wallet/domain/WalletTest.java

First version to start the discussion. I would suggest reading everything first, and adding comments in the second round. Unless it's typo or gramma.

docs: deduplication strategies documentation

---

docs/.vale.ini
docs/src/modules/java/pages/shopping-cart-quickstart.adoc

Just a couple of tweaks for consistency and phrasing.

minor phrasing and tone changes to shopping cart sample

---

.github/workflows/documentation.yml
docs/src/modules/java/pages/http-endpoints.adoc
docs/src/modules/operations/pages/projects/create-project.adoc

Trying to make sure we build docs before merging to avoid issues as [this](https://github.com/akka/akka-sdk/actions/runs/13894884585/job/38873234239).

ci: build docs on PR

---

docs/src/modules/reference/pages/release-notes.adoc

A bit of language simplification.

docs: slight updates to the flagship release notes

---

samples/capacity-allocation/src/main/java/com/example/api/CapacityEndpoint.java
samples/capacity-allocation/src/main/java/com/example/application/UserActivityEntity.java

disable UserActivityEntity if allocation rules are empty

---

Makefile
docs/src/modules/java/pages/components/index.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_local_console.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_local_services_components.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_local_services_components_get-state.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_local_services_components_get-workflow.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_local_services_components_list-events.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_local_services_components_list-ids.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_organizations_users.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_organizations_users_list-bindings.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_projects_regions.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_projects_regions_remove.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_services_components.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_services_components_get-state.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_services_components_get-workflow.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_services_components_list-events.adoc
docs/src/modules/reference/pages/cli/akka-cli/index.adoc
docs/src/modules/reference/pages/release-notes.adoc

Publish latest doc changes

---

docs/src/modules/java/pages/views.adoc
samples/event-sourced-counter-brokers/README.md
samples/event-sourced-counter-brokers/src/main/java/counter/api/CounterEndpoint.java
samples/event-sourced-counter-brokers/src/main/java/counter/application/CounterTopicView.java

Updated to actually show a view consuming a topic
References
- https://github.com/akka/akka-sdk/issues/332

docs: Better sample for views from topic

---

akka-javasdk-tests/src/test/java/akkajavasdk/HttpEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/http/TestEndpoint.java
akka-javasdk-tests/src/test/resources/META-INF/akka-javasdk-components.conf
akka-javasdk/src/main/java/akka/javasdk/http/RequestBuilder.java
akka-javasdk/src/main/scala/akka/javasdk/impl/http/HttpClientImpl.scala

Sadly can't be done with the same method because of erasure.

feat: HTTP client JSON array response body support

---

docs/src/modules/java/pages/views.adoc

Tiny follow up of https://github.com/akka/akka-sdk/pull/333

docs: remove outdated note

---

docs/src/modules/java/pages/component-and-service-calls.adoc
docs/src/modules/operations/pages/regions/index.adoc

Close #321 
Close https://github.com/lightbend/kalix-runtime/issues/3660

docs: rewording paragraph and add link

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EntitySerializationChecker.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EventSourcedEntityEffectsRunner.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EventSourcedTestKit.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/KeyValueEntityTestKit.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/eventsourced/CounterEventSourcedEntity.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/eventsourced/CounterEventSourcedEntityTest.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/keyvalueentity/CounterKeyValueEntityTest.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/keyvalueentity/CounterValueEntity.java
akka-javasdk-tests/src/test/java/akkajavasdk/KeyValueEntityTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/ViewIntegrationTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/keyvalueentities/customer/CustomerEntity.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/views/user/UsersView.java
akka-javasdk/src/main/scala/akka/javasdk/impl/client/EntityClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/client/ViewClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/reflection/Reflect.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/serialization/JsonSerializer.scala

References https://github.com/lightbend/kalix-runtime/issues/3659

fix: Correct deserialization of collections in component client returns

---

docs/src/modules/reference/pages/release-notes.adoc

References https://github.com/akka/akka/releases/tag/v2.10.3

docs: Akka core 2.10.3 release notes

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EntitySerializationChecker.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EventSourcedEntityEffectsRunner.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EventSourcedTestKit.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/KeyValueEntityTestKit.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/eventsourced/CounterEventSourcedEntity.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/eventsourced/CounterEventSourcedEntityTest.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/keyvalueentity/CounterKeyValueEntityTest.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/keyvalueentity/CounterValueEntity.java
akka-javasdk-tests/src/test/java/akkajavasdk/HttpEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/KeyValueEntityTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/ViewIntegrationTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/http/TestEndpoint.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/keyvalueentities/customer/CustomerEntity.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/views/user/UsersView.java
akka-javasdk-tests/src/test/resources/META-INF/akka-javasdk-components.conf
akka-javasdk/src/main/java/akka/javasdk/http/RequestBuilder.java
akka-javasdk/src/main/scala/akka/javasdk/impl/client/EntityClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/client/ViewClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/http/HttpClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/reflection/Reflect.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/serialization/JsonSerializer.scala
docs/src/modules/java/pages/component-and-service-calls.adoc
docs/src/modules/java/pages/views.adoc
docs/src/modules/java/pages/workflows.adoc
docs/src/modules/operations/pages/regions/index.adoc
docs/src/modules/reference/pages/release-notes.adoc
samples/event-sourced-counter-brokers/README.md
samples/event-sourced-counter-brokers/src/main/java/counter/api/CounterEndpoint.java
samples/event-sourced-counter-brokers/src/main/java/counter/application/CounterTopicView.java
samples/transfer-workflow/src/main/java/com/example/transfer/application/TransferWorkflow.java

Publish doc changes

---

docs/src/modules/reference/pages/release-notes.adoc

* and fix the link to use xref

docs: Use sidebar in release notes

---

.github/kafka.yml
samples/event-sourced-counter-brokers/docker-compose.yml

Bumping Kafka to follow hint from a Kalix SDK user.
References
- https://github.com/lightbend/kalix-jvm-sdk/issues/2289

bump: Confluent Kafka/Zookeeper 7.9.0 in Docker compose

---

docs/src/modules/self-managed/pages/configuring.adoc
samples/doc-snippets/standalone/service.yml

Should be enough with ClusterIP

docs: ClusterIP in k8s service

---

docs/src/modules/concepts/pages/declarative-effects.adoc

Just added a summary of effects so that I can see them all in one place rather than clicking to each page.

adding cross reference table for available effects

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithTimer.java
akka-javasdk/src/main/java/akka/javasdk/timer/TimerScheduler.java
akka-javasdk/src/main/scala/akka/javasdk/impl/timer/TimerSchedulerImpl.scala
docs/src/modules/java/pages/timed-actions.adoc
samples/choreography-saga-quickstart/src/main/java/user/registry/application/UniqueEmailConsumer.java
samples/doc-snippets/src/main/java/com/example/application/MyConsumer.java
samples/endpoint-jwt/src/main/java/hellojwt/api/HelloJwtEndpoint.java
samples/reliable-timers/src/main/java/com/example/api/OrderEndpoint.java
samples/tracing/src/main/java/com/example/tracing/api/TracingEndpoint.java
samples/transfer-workflow-compensation/src/main/java/com/example/transfer/application/TransferWorkflow.java

References https://github.com/lightbend/kalix-runtime/issues/3719
On top of #340

feat: blocking timers calls for virtual threads

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk-tests/src/test/java/akkajavasdk/GrpcEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/JwtEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestGrpcServiceImpl.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestJwtsGrpcServiceImpl.java
build.sbt
project/Common.scala
project/Dependencies.scala
project/SamplesCompilationProject.scala
samples/doc-snippets/src/main/java/com/example/api/CustomerGrpcEndpointImpl.java
samples/doc-snippets/src/main/java/com/example/api/ExampleGrpcEndpointImpl.java
samples/doc-snippets/src/main/java/com/example/callanotherservice/CallExternalGrpcEndpointImpl.java
samples/doc-snippets/src/main/java/com/example/callanotherservice/DelegatingGrpcEndpointImpl.java
samples/doc-snippets/src/test/java/com/example/api/ExampleGrpcEndpointTest.java
samples/event-sourced-customer-registry-subscriber/src/main/java/customer/api/DelegateCustomerGrpcEndpointImpl.java
samples/event-sourced-customer-registry/src/main/java/customer/api/CustomerGrpcEndpointImpl.java
samples/event-sourced-customer-registry/src/test/java/customer/api/CustomerGrpcIntegrationTest.java

On top of #340 
References https://github.com/lightbend/kalix-runtime/issues/3720

feat: virtual thread/blocking APIs for gRPC

---

docs/src/modules/self-managed/pages/configuring.adoc
samples/doc-snippets/standalone/deployment.yml

docs: Add missing podcost-crd.yml to standalone docs

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/FraudDetectionResult.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/TransferWorkflow.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/TransferWorkflowWithFraudDetection.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/TransferWorkflowWithoutInputs.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithDefaultRecoverStrategy.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithRecoverStrategy.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithStepTimeout.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithTimeout.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithoutInitialState.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/hierarchy/TextWorkflow.java
akka-javasdk/src/main/java/akka/javasdk/workflow/StepBuilder.java
akka-javasdk/src/main/java/akka/javasdk/workflow/Workflow.java
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/ReflectiveWorkflowRouter.scala
akka-javasdk/src/test/java/akka/javasdk/workflow/TestWorkflowSerialization.java
docs/src/modules/java/pages/workflows.adoc
project/SamplesCompilationProject.scala
samples/ask-akka-agent/src/main/java/akka/ask/indexer/application/RagIndexingWorkflow.java
samples/key-value-shopping-cart/README.md
samples/transfer-workflow-compensation/src/main/java/com/example/transfer/application/TransferWorkflow.java
samples/transfer-workflow/src/main/java/com/example/transfer/application/TransferWorkflow.java

References https://github.com/lightbend/kalix-runtime/issues/3718

feat: blocking/virtual thread APIs for workflows

---

docs/src/modules/java/pages/grpc-endpoints.adoc
docs/src/modules/java/pages/shopping-cart/quickstart.adoc
samples/ask-akka-agent/src/main/resources/flat-doc/author-your-first-service.md
samples/ask-akka-agent/src/main/resources/flat-doc/http-endpoints.md
samples/event-sourced-counter-brokers/src/main/java/counter/application/CounterEventsConsumer.java

References https://github.com/lightbend/kalix-runtime/issues/3730

docs: Some improvements/alignment after virtual threads API changes

---

docs/src/modules/reference/pages/migration-guide.adoc

References https://github.com/lightbend/kalix-runtime/issues/3730

docs: Virtual threads migration guide

---

docs/src/modules/java/pages/timed-actions.adoc
samples/ask-akka-agent/src/main/resources/flat-doc/timed-actions.md
samples/choreography-saga-quickstart/src/main/java/user/registry/application/UniqueEmailConsumer.java
samples/reliable-timers/src/main/java/com/example/api/OrderEndpoint.java
samples/transfer-workflow-compensation/src/main/java/com/example/transfer/application/TransferWorkflow.java

fix: align documentation with new Timer API

---

akka-javasdk-tests/src/test/java/akkajavasdk/ViewIntegrationTest.java
docs/src/modules/reference/pages/release-notes.adoc

References https://github.com/akka/akka-sdk/issues/377
Need some help with the sales-pitchy sidebar thing.

docs: Release notes for runtime 1.4.8 and SDK 3.3.0

---

docs/src/modules/operations/pages/regions/index.adoc
docs/src/modules/operations/pages/services/deploy-service.adoc
samples/ask-akka-agent/src/main/resources/flat-doc/deploy-service.md

References #395 
Found not only in region's page.

fix: spec instead service

---

.github/workflows/docs-prod.yml
.github/workflows/docs-wip.yml
docs/bin/docs2markdown.sh

Follow up to https://github.com/akka/akka-sdk/pull/403

chore: Don't update ask-akka-agent from script

---

docs/src/modules/java/pages/author-your-first-service.adoc

https://typesafe.slack.com/archives/C07JV3ED7V4/p1746049250979679

fix: typo helloword

---

docs/bin/docs2markdown.sh

build: sed syntax in docs2markdown.sh

---

akka-javasdk-maven/akka-javasdk-archetype/pom.xml
akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk-maven/pom.xml
samples/ask-akka-agent/pom.xml
samples/choreography-saga-quickstart/pom.xml
samples/doc-snippets/pom.xml
samples/endpoint-jwt/pom.xml
samples/event-sourced-counter-brokers/pom.xml
samples/event-sourced-customer-registry-subscriber/pom.xml
samples/event-sourced-customer-registry/pom.xml
samples/key-value-counter/pom.xml
samples/key-value-customer-registry/pom.xml
samples/key-value-shopping-cart/pom.xml
samples/reliable-timers/pom.xml
samples/shopping-cart-quickstart/pom.xml
samples/shopping-cart-with-view/pom.xml
samples/spring-dependency-injection/pom.xml
samples/tracing/pom.xml
samples/transfer-workflow-compensation/pom.xml
samples/transfer-workflow/pom.xml
samples/view-store/pom.xml

Auto-PR was not created, created issue https://github.com/lightbend/kalix-runtime/issues/3808

chore: bump SDK versions to 3.3.1

---

.github/workflows/docs-prod.yml
.github/workflows/docs-wip.yml
.gitignore
docs/bin/docs2markdown.sh
docs/src/modules/ROOT/pages/llms.txt
docs/src/modules/java/pages/ai-coding-assistant-guidelines.adoc

To support https://llmstxt.org
If I understand it correctly we will be able to generate additional llm context files from the llms.txt using https://llmstxt.org/nbdev.html#generating-context-files but first we must publish the markdown files.
On top of https://github.com/akka/akka-sdk/pull/403

docs: llms.txt

---

.github/workflows/docs-wip.yml

Sorry, I should have tested previous PR with workflow dispatch. I have tried this.

build: Another CI permission

---

.github/workflows/docs-prod.yml
.github/workflows/docs-wip.yml
.github/workflows/pr-akka-samples.yml
.gitignore
docs/bin/docs2markdown.sh
docs/src/modules/ROOT/pages/llms.txt
docs/src/modules/java/nav.adoc
docs/src/modules/java/pages/ai-coding-assistant-guidelines.adoc
docs/src/modules/java/pages/ask-akka/endpoints.adoc
samples/ask-akka-agent/src/main/java/akka/ask/agent/api/AskHttpEndpoint.java
samples/ask-akka-agent/src/main/java/akka/ask/agent/api/UiEndpoint.java
samples/ask-akka-agent/src/main/java/akka/ask/agent/api/UsersEndpoint.java

Publish latest docs

---

.github/workflows/docs-prod.yml

Corresponding to https://github.com/akka/akka-sdk/pull/425

build: llms-txt in docs-prod ci

---

.github/workflows/docs-prod.yml

Publish llms txt

---

.github/workflows/docs-prod.yml

Publish docs: llms.txt to the right place

---

docs/src/modules/reference/pages/release-notes.adoc
docs/src/modules/reference/pages/release-notes/2025-05-06-akka-25.05-released.adoc

References https://github.com/lightbend/akka-meta/issues/587

docs: Akka 25.05 release notes

---

Makefile
docs/src/modules/reference/pages/cli/akka-cli/akka_local_console.adoc
docs/src/modules/reference/pages/release-notes.adoc
docs/src/modules/reference/pages/release-notes/2025-05-06-akka-25.05-released.adoc

Publish release notes

---

.github/workflows/pr-akka-samples.yml
.github/workflows/update-sdk-version.yml

Refs https://github.com/lightbend/kalix-runtime/issues/3808

ci: likely fix for auto PRs not being created

---

docs/src/modules/java/pages/key-value-entities.adoc
samples/key-value-counter/src/main/java/com/example/application/CounterEntity.java

docs: small improvements in KV page

---

docs/src/modules/java/pages/http-endpoints.adoc

docs: Small typo in static resource section 

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
project/Dependencies.scala

**After the Runtime version reaches prod**, please mark as ready, review and merge.  [5901c502fa768421b93d6f339179a092ccd3c5a2](https://github.com/lightbend/kalix-runtime/commit/5901c502fa768421b93d6f339179a092ccd3c5a2)

Auto PR - Akka Runtime version 1.4.11

---

docs/src/modules/reference/pages/release-notes.adoc

References
- https://github.com/akka/akka-sdk/pull/434

docs: Runtime 1.4.11 in release notes

---

samples/ask-akka-agent/src/main/java/akka/ask/Bootstrap.java
samples/ask-akka-agent/src/main/java/akka/ask/agent/application/Knowledge.java
samples/ask-akka-agent/src/main/java/akka/ask/agent/application/NewAskAkkaAgent.java
samples/ask-akka-agent/src/main/java/akka/ask/agent/application/StructuredAskAkkaAgent.java

* Adding knowledge (via RAG or other way) is an application concern.
* This adds an example of how to do that with Langchain4j RAG

feat: Add knowledge to the user message (RAG)

---

akka-javasdk/src/main/java/akka/javasdk/agent/Agent.java
akka-javasdk/src/main/java/akka/javasdk/agent/ModelProvider.java
akka-javasdk/src/main/resources/reference.conf
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentEffectImpl.scala
samples/ask-akka-agent/src/main/java/akka/ask/agent/application/StructuredAskAkkaAgent.java

* and api docs for the ModelProvider

chore: Rename modelProvider to model in the effect builder

---

docs/src/modules/reference/pages/release-notes/2025-05-06-akka-25.05-released.adoc

docs: add ap-jdbc #904 to release notes (#467)

---

docs/src/modules/reference/pages/descriptors/service-descriptor.adoc

This PR adds information about the updated service descriptor.

docs: service descriptor runtime field

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
project/Dependencies.scala
project/plugins.sbt

(cherry picked from commit e8f28c2cdeaab6863b586a41457e840030a972a2)
Do not squash, to avoid merge conflicts with agent-dev

chore: runtime bump + akka deps (#450)

---

.github/workflows/docs-static.yml
.github/workflows/docs-wip.yml

Branch should come from the
```
on:
workflow_dispatch:
push:
branches:
- 'main'
```

build: Publish wip docs from any branch

---

docs/src/modules/reference/pages/release-notes.adoc
docs/src/modules/reference/pages/security-announcements/akka-management-cve-2025-46548.adoc
docs/src/modules/reference/pages/security-announcements/index.adoc

docs: Akka management announcement

---

akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/README.md
akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/api/HelloWorldEndpoint.java
akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/application/HelloWorldAgent.java
akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/src/main/resources/application.conf
docs/src/modules/concepts/pages/architecture-model.adoc
docs/src/modules/getting-started/pages/author-your-first-service.adoc
docs/src/modules/getting-started/pages/index.adoc
docs/src/modules/getting-started/pages/samples.adoc
docs/src/modules/getting-started/pages/session.adoc
docs/src/modules/java/pages/index.adoc
samples/doc-snippets/pom.xml
samples/doc-snippets/src/main/java/com/example/api/HelloWorldEndpoint.java
samples/doc-snippets/src/main/java/com/example/application/HelloWorldAgent.java

* Author your first agentic service
* Add agent to maven archetype

docs: Add agent to getting started

---

docs/src/modules/ROOT/pages/index.adoc
docs/src/modules/concepts/nav.adoc
docs/src/modules/concepts/pages/concepts.adoc
docs/src/modules/concepts/pages/distributed-systems.adoc
docs/src/modules/concepts/pages/index.adoc

Back to "Understanding" as main menu title with Concepts and Distributed Systems as new subpages.

docs: understanding pages

---

docs/src/modules/concepts/pages/concepts.adoc
docs/styles/config/vocabularies/Akka/accept.txt

Reflects the state of the source document as of 1pm ET on Fri Jun 13. Source document may have changed since then.
Closes: lightbend/kalix#13602

docs: foundational agentic AI systems concepts

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/agent/SessionMemoryEntityTest.java
akka-javasdk/src/main/java/akka/javasdk/agent/SessionMemoryEntity.java
akka-javasdk/src/main/java/akka/javasdk/agent/SessionMessage.java
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala
docs/src/modules/java/pages/agents.adoc
samples/doc-snippets/src/main/java/com/example/application/CompactionAgent.java
samples/doc-snippets/src/main/java/com/example/application/SessionMemoryConsumer.java
samples/doc-snippets/src/test/java/com/example/application/CompactionAgentIntegrationTest.java

and in second commit d343dde1dfb1eacadbbd6c55e1c05215022d5b6a also remove input and output tokens from session memory

chore: Trigger compaction based on size

---

docs/supplemental_ui/partials/notification-banner.hbs

@beritou request came in from Tyler to change the text on the banner. Is it possible to have this deployed sooner than later?

Update banner text

---

docs/src/modules/concepts/pages/concepts.adoc

docs(concepts): add distributed system properties

---

docs/src/modules/ROOT/partials/concepts-intro.adoc
docs/styles/config/vocabularies/Akka/accept.txt

docs(concepts): clarify memory section

---

docs/src/modules/concepts/pages/concepts.adoc
docs/styles/config/vocabularies/Akka/accept.txt

docs(concepts): expand component descriptions

---

samples/ask-akka-agent/README.md

This sample is lacking the intro section describing the context, the components used and eventually a sequence diagram as well but I'm jumping tasks so decided to open already with this. Might follow up later.
Refs https://github.com/lightbend/kalix-runtime/issues/3954

docs: add deploy runbook to ask akka sample

---

docs/src/modules/ROOT/pages/index.adoc
docs/src/modules/concepts/pages/concepts.adoc
docs/styles/config/vocabularies/Akka/accept.txt

docs(concepts): update page title

---

samples/helloworld-agent/README.md

Refs https://github.com/lightbend/kalix-runtime/issues/3954

docs(sample): update readme with secret setup step

---

docs/src/modules/concepts/pages/concepts.adoc

docs(concepts): consolidate runtimes content

---

docs/src/modules/ROOT/partials/concepts-intro.adoc

chore(docs): hyperlink component names

---

docs/src/modules/ROOT/partials/concepts-intro.adoc
docs/src/modules/concepts/pages/concepts.adoc

chore(docs): tighten table spacing

---

akka-javasdk/src/main/java/akka/javasdk/annotations/Description.java
akka-javasdk/src/main/java/akka/javasdk/annotations/FunctionTool.java
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/ToolExecutor.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/agent/ToolExecutorSpec.scala
docs/src/modules/java/pages/agents.adoc
samples/multi-agent/pom.xml
samples/multi-agent/src/main/java/demo/multiagent/application/agents/FakeWeatherService.java
samples/multi-agent/src/main/java/demo/multiagent/application/agents/WeatherService.java
samples/multi-agent/src/main/java/demo/multiagent/application/agents/WeatherServiceImpl.java

Refs: https://github.com/lightbend/kalix-runtime/issues/3938

feat: support optional tool parameters

---

docs/src/modules/getting-started/pages/author-your-first-service.adoc
docs/src/modules/getting-started/pages/build-and-deploy-shopping-cart.adoc
docs/src/modules/java/pages/running-locally.adoc
samples/ask-akka-agent/src/main/resources/md-docs/author-your-first-service.html.md
samples/ask-akka-agent/src/main/resources/md-docs/quickstart.html.md
samples/ask-akka-agent/src/main/resources/md-docs/running-locally.html.md
samples/shopping-cart-quickstart/README.md

This update the docs to be compatible with changes made to the CLI `local` command.

chore: Update the docs with CLI changes

---

docs/src/modules/java/pages/agents.adoc
docs/src/modules/java/pages/event-sourced-entities.adoc
docs/src/modules/java/pages/http-endpoints.adoc
docs/src/modules/java/pages/key-value-entities.adoc

Also takes into account the idea that the reader might not know what all the other components are at the time.

Updates the "identify the agent" section to be more clear

---

akka-javasdk/src/main/java/akka/javasdk/agent/ModelProvider.java
akka-javasdk/src/main/resources/reference.conf
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala
akka-javasdk/src/test/scala/akka/javasdk/agent/ModelProviderSpec.scala
docs/src/modules/java/pages/agents.adoc
docs/src/modules/java/pages/model-provider-details.adoc

Depends on upstream support in https://github.com/lightbend/kalix-runtime/pull/3962

feat: Support for Hugging Face models

---

docs/src/modules/concepts/pages/concepts.adoc
docs/styles/config/vocabularies/Akka/accept.txt

docs(concepts): update/move service packaging

---

akka-javasdk-tests/tempo.yaml
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
docs/src/modules/getting-started/nav.adoc
docs/src/modules/getting-started/pages/ask-akka-agent/endpoints.adoc
docs/src/modules/getting-started/pages/ask-akka-agent/index.adoc
docs/src/modules/getting-started/pages/ask-akka-agent/indexer.adoc
docs/src/modules/getting-started/pages/ask-akka-agent/rag.adoc
docs/src/modules/getting-started/pages/author-your-first-service.adoc
docs/src/modules/getting-started/pages/index.adoc
docs/src/modules/getting-started/pages/planner-agent/index.adoc
docs/src/modules/getting-started/pages/planner-agent/preferences.adoc
docs/src/modules/getting-started/pages/samples.adoc
docs/src/modules/reference/pages/cli/akka-cli/akka_services_expose.adoc
samples/doc-snippets/src/main/java/agent_guide/part1/ActivityAgent.java
samples/doc-snippets/src/main/java/agent_guide/part1/ActivityEndpoint.java
samples/doc-snippets/src/main/java/agent_guide/part2/ActivityAgent.java
samples/doc-snippets/src/main/java/agent_guide/part2/ActivityEndpoint.java
samples/doc-snippets/src/main/java/agent_guide/part2/PreferencesEntity.java

Would need more explanation, but wanted to see the flow and structure first.

docs: Getting started agent guide, part 1 and 2

---

docs/src/modules/ROOT/pages/index.adoc
docs/src/modules/concepts/pages/deployment-model.adoc
docs/src/modules/concepts/pages/development-process.adoc
docs/src/modules/getting-started/pages/build-and-deploy-shopping-cart.adoc
docs/src/modules/operations/nav.adoc
docs/src/modules/operations/pages/akka-platform.adoc
docs/src/modules/operations/pages/index.adoc
docs/src/modules/operations/pages/platform-features.adoc
samples/ask-akka-agent/README.md

Overall basket that names everything is Akka Agentic Platform
Four offerings:
1. Akka Orchestration
1. Akka Agents
1. Akka Memory
1. Akka Streaming
Two formal ways to build: 
* Akka SDK and 
* Akka Libraries.
Two formal ways to operate:
* Self-Managed Operations
* Akka Automated Operations

docs: augmenting Akka Agentic Platform and Akka Automated Operations

---

docs/src/modules/ROOT/partials/concepts-intro.adoc

docs(concepts): add section heading

---

samples/multi-agent/src/main/java/demo/multiagent/api/ActivityEndpoint.java

Noticed when running this sample.

sample: remove extra space in multi-agent created path

---

docs/src/modules/ROOT/pages/index.adoc

docs: revise landing page intro statement

---

docs/src/modules/getting-started/pages/samples.adoc

Renames "samples" to "additional samples"
Standardize the headings
Adds a table of contents ("On this Page")

adding table of contents to additional samples page

---

docs/src/modules/ROOT/attachments/akka-code-init.json

This enumerates samples for the `akka code init` command to consume.

chore: Add Akka code init directory

---

docs/src/modules/getting-started/pages/author-your-first-service.adoc

chore: Shallow clone of helloworld

---

docs/src/modules/getting-started/pages/planner-agent/activity.adoc
samples/doc-snippets/src/main/java/agent_guide/part1/ActivityEndpoint.java
samples/doc-snippets/src/main/java/agent_guide/part2/ActivityAgent.java
samples/doc-snippets/src/main/java/agent_guide/part2/ActivityEndpoint.java
samples/doc-snippets/src/main/java/agent_guide/part4/ActivityEndpoint.java
samples/doc-snippets/src/main/java/agent_guide/part5/ActivityEndpoint.java
samples/multi-agent/src/main/java/demo/multiagent/application/ActivityAgent.java
samples/multi-agent/src/main/java/demo/multiagent/application/SummarizerAgent.java

chore: Minor fixes in getting started

---

akka-javasdk/src/main/scala/akka/javasdk/impl/JsonSchema.scala
akka-javasdk/src/test/java/akka/javasdk/impl/SomeToolInput.java
akka-javasdk/src/test/scala/akka/javasdk/impl/JsonSchemaSpec.scala

References https://github.com/lightbend/kalix-runtime/issues/3990

chore: Support recursive types, and more stdlib types in JsonSchema creation

---

docs/src/modules/ROOT/attachments/akka-code-init.json

Fix some typos in akka-code-init.

chore: Fix some typos in akka-code-init

---

docs/src/modules/concepts/pages/index.adoc

Makes the index page of the "Understanding" section more complete and lists all sub-pages.
https://doc.akka.io/concepts/index.html

docs: understanding index page

---

docs/src/modules/reference/pages/release-notes.adoc

Fat fingers made the number too big.

docs: correct CLI version

---

docs/src/modules/getting-started/pages/author-your-first-service.adoc

Missing target directory
Follow up on https://github.com/akka/akka-sdk/pull/725

chore: akka code init dir

---

docs/src/modules/getting-started/pages/addview.adoc
docs/src/modules/getting-started/pages/build-and-deploy-shopping-cart.adoc
docs/src/modules/java/pages/event-sourced-entities.adoc
samples/shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java
samples/shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCart.java
samples/shopping-cart-with-view/src/main/java/shoppingcart/application/ShoppingCartEntity.java
samples/shopping-cart-with-view/src/main/java/shoppingcart/application/UserEntity.java
samples/shopping-cart-with-view/src/main/java/shoppingcart/domain/ShoppingCart.java
samples/shopping-cart-with-view/src/main/java/shoppingcart/domain/User.java
samples/shopping-cart-with-view/src/main/java/shoppingcart/domain/UserState.java
samples/shopping-cart-with-view/src/test/java/shoppingcart/ShoppingCartIntegrationTest.java
samples/shopping-cart-with-view/src/test/java/shoppingcart/application/ShoppingCartTest.java

Explains why the AI assistant insists on generating that style

chore: Update shopping cart according to coding guidelines

---

samples/event-sourced-counter-brokers/docker-compose.yml
samples/event-sourced-counter-brokers/src/test/java/counter/application/CounterWithRealPubSubIntegrationTest.java

References https://github.com/lightbend/kalix-runtime/issues/4006

chore: Wait for google pubsub topic to be created before testing it

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/TransferWorkflow.java
akka-javasdk/src/main/java/akka/javasdk/workflow/Workflow.java
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/ReflectiveWorkflowRouter.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala

First part towards step methods. 
For now, still using `call/andThen`, but registering them automatically using reflection.

feat: auto-registration of step methods

---

docs/src/modules/concepts/nav.adoc
docs/src/modules/concepts/pages/index.adoc
docs/src/modules/concepts/pages/inter-agent-comms.adoc

Adds the agent-to-agent communications document to the `Understanding` section.

Adding inter-agent comms doc

---

docs/src/modules/operations/pages/services/view-data.adoc

> Command "list-entity-ids" is deprecated, please use `list-ids` command instead

list-ids replaces list-entity-ids

---

docs/src/modules/concepts/pages/inter-agent-comms.adoc

does some cleanup on the path avoid and adopt table.

cleaning up adopt and avoid table

---

docs/src/modules/concepts/pages/concepts.adoc

docs(concepts): reduce component icon size

---

docs/src/modules/concepts/pages/distributed-systems.adoc

docs(concepts): clarify distributed systems page

---

docs/src/modules/concepts/pages/concepts.adoc

docs(concepts): consolidate component overview

---

.github/workflows/ci.yml
samples/helloworld-agent/src/test/resources/application.conf

Otherwise, the akka-sample build will fail

chore: running IT for helloworld-agent sample

---

docs/src/modules/java/nav.adoc
docs/src/modules/java/pages/asynchronous.adoc

Per conversation with Tyler, adding a small page that is explicit about async vs. sync.

adding small page on async

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/TransferWorkflow.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithDefaultRecoverStrategy.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithRecoverStrategy.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithStepTimeout.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithTimeout.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithTimer.java
akka-javasdk/src/main/java/akka/javasdk/workflow/Workflow.java
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala
docs/src/modules/java/pages/workflows.adoc
samples/doc-snippets/src/main/java/com/example/application/AgentTeamWorkflow.java
samples/multi-agent/src/main/java/demo/multiagent/application/AgentTeamWorkflow.java
samples/transfer-workflow-compensation/src/main/java/com/example/Bootstrap.java
samples/transfer-workflow-compensation/src/main/java/com/example/transfer/application/FraudDetectionService.java
samples/transfer-workflow-compensation/src/main/java/com/example/transfer/application/TransferWorkflow.java

Docs are in draft. I'm experimenting with some ideas in the transfer compensation sample that I plan to use as snippets later.

feat: remove workflow timeout

---

project/SamplesCompilationProject.scala

This will run the formatter whenever there are files to compile in the samples.

chore: format samples from sbt

---

docs/src/modules/getting-started/pages/author-your-first-service.adoc

Show the hidden repo flag for immediate creation without the assistant.

docs: code init with repo flag

---

akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ConsumerImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/keyvalueentity/KeyValueEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/telemetry/Telemetry.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/timedaction/TimedActionImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala

Remove all the component tracing that has been moved to the runtime. Needs updated runtime.

chore: remove component tracing

---

akka-javasdk/src/main/java/akka/javasdk/agent/ModelProvider.java
akka-javasdk/src/main/resources/reference.conf
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala
samples/helloworld-agent/src/main/resources/application.conf

Refs https://github.com/akka/akka-sdk/issues/880
Requires a new runtime release with https://github.com/lightbend/kalix-runtime/pull/4142

feat: Support GPT-5 maxCompletionTokens

---

docs/bin/generate_cli_docs.sh
docs/src/modules/reference/pages/cli/akka-cli/akka_code_init.adoc
docs/src/modules/reference/pages/cli/akka-cli/cli-index-header.template.txt
docs/src/modules/reference/pages/cli/akka-cli/index.adoc
samples/ask-akka-agent/src/main/resources/md-docs/author-your-first-service.html.md

References
- https://github.com/akka/akka-sdk/pull/912
- https://github.com/akka/akka-sdk/pull/906

docs: add akka code init to CLI index generation

---

docs/src/modules/concepts/pages/grpc-vs-http-endpoints.adoc

References https://github.com/lightbend/kalix/issues/13632

docs: Mention MCP on endpoint design choice page

---

akka-javasdk/src/main/java/akka/javasdk/http/HttpResponses.java

References https://github.com/lightbend/kalix-runtime/issues/3964
This makes the error go to service logs instead of runtime (Akka HTTP server) logs if SSE stream fails.

chore: Better error handling for SSE streams

---

.github/workflows/ci.yml
akka-javasdk-parent/pom.xml
akka-javasdk-tests/src/test/java/akkajavasdk/components/agent/AgentIntegrationTest.java
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/keyvalueentity/KeyValueEntityImpl.scala
project/Dependencies.scala

In preparation for next runtime release

bump: Runtime 1.5.13

---

akka-javasdk/src/main/java/akka/javasdk/agent/ModelProvider.java
akka-javasdk/src/main/java/akka/javasdk/agent/RemoteMcpTools.java
akka-javasdk/src/main/resources/reference.conf
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/RemoteMcpToolsImpl.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/agent/ToolExecutorSpec.scala
project/Dependencies.scala

References https://github.com/lightbend/akka-runtime/pull/4064
Depends on runtime change https://github.com/lightbend/akka-runtime/pull/4245

feat: User configurable timeouts and retries for model and MCP
