akka/akka-sdk

docs/README.md
docs/src/modules/ROOT/pages/index.adoc
docs/src/modules/java/pages/author-your-first-service.adoc

Remove some details from the "Hello World" page.
- don't mention Jackson and other serialization details
Put some structure on getting started options: "hands on" vs "understanding"

docs: less detail in Hello World

---

.github/workflows/docs-cli-updates.yml

Mac vs Linux strikes again. Adding some debugging help in case this doesn't cut it.

chore: sed syntax in CLI version workflow

---

docs/src/modules/reference/pages/release-notes.adoc

Fix wrong version in release notes text.
- https://github.com/akka/akka-sdk/pull/53#pullrequestreview-2476064011

docs: SDK 3.0.1 release notes

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EventSourcedTestKit.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/EventingTestKit.java
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/TestKit.java
akka-javasdk-testkit/src/main/scala/akka/javasdk/testkit/impl/EventingTestKitImpl.scala
akka-javasdk-testkit/src/test/scala/akka/javasdk/testkit/impl/IncomingMessagesImplSpec.scala
akka-javasdk-testkit/src/test/scala/akka/javasdk/testkit/impl/OutgoingMessagesImplSpec.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/serialization/JsonSerializer.scala

* it's still heavily based on proto underneath

chore: Use JsonSerializer in EventingTestKit

---

akka-javasdk-annotation-processor-tests/entites-and-views-descriptors/src/main/java/com/example/AbstractInbetweenKvEntity2.java
akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk-testkit/src/main/scala/akka/javasdk/testkit/impl/EventingTestKitImpl.scala
akka-javasdk-tests/src/test/java/akkajavasdk/WorkflowTest.java
akka-javasdk/src/main/scala/akka/javasdk/impl/CommandHandler.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/ComponentDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/InvocationContext.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ConsumerImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ReflectiveConsumerRouter.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/reflection/ParameterExtractor.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/serialization/JsonSerializer.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/timedaction/TimedActionImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/ConsumersImplSpec.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/action/TimedActionHandlerSpec.scala
project/Dependencies.scala

Workflows tests are disabled, but the rest are green

chore: consuming and producing without proto desc SDK changes

---

akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/keyvalueentity/KeyValueEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala

* once per class instead of for each entity instance
* used for the command handler lookup

chore: Populate ComponentDescriptor once, in SdkRunner

---

LICENSE
akka-javasdk-maven/akka-javasdk-archetype/pom.xml
akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk-maven/pom.xml
docs/src/modules/java/pages/event-sourced-entities.adoc
docs/src/modules/reference/pages/release-notes.adoc
samples/choreography-saga-quickstart/pom.xml
samples/doc-snippets/pom.xml
samples/endpoint-jwt/pom.xml
samples/event-sourced-counter-brokers/pom.xml
samples/event-sourced-customer-registry-subscriber/pom.xml
samples/event-sourced-customer-registry/pom.xml
samples/key-value-counter/pom.xml
samples/key-value-customer-registry/pom.xml
samples/key-value-shopping-cart/pom.xml
samples/reliable-timers/pom.xml
samples/shopping-cart-quickstart/pom.xml
samples/spring-dependency-injection/pom.xml
samples/tracing/pom.xml
samples/transfer-workflow-compensation/pom.xml
samples/transfer-workflow/pom.xml
samples/view-store/pom.xml

chore: update release date license and sdk samples to 3.0.2 (#85)

---

akka-javasdk/src/main/java/akka/javasdk/workflow/Workflow.java
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/ReflectiveWorkflowRouter.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala
samples/transfer-workflow-compensation/src/main/java/com/example/transfer/application/TransferWorkflow.java

Create a new instance of workflow on each iteration: handle command, execute step and transition. 
This make it safe to capture the workflow state in flatMaps. 
Also, since we serialize/deserialize the state each time, the state on which a user can operate is always a unique and fresh object.

chore: make workflow stateless

---

akka-javasdk/src/main/java/akka/javasdk/JsonSupport.java
akka-javasdk/src/main/java/akka/javasdk/http/HttpResponses.java
akka-javasdk/src/main/scala/akka/javasdk/impl/client/ViewClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/http/HttpClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/serialization/JsonSerializer.scala
akka-javasdk/src/test/scala/akka/javasdk/JsonSupportSpec.scala
docs/src/modules/java/pages/serialization.adoc
samples/doc-snippets/src/main/java/com/example/api/ExampleEndpoint.java
samples/event-sourced-counter-brokers/src/it/java/counter/application/CounterWithRealKafkaIntegrationTest.java
samples/event-sourced-customer-registry/src/test/java/customer/domain/CustomerEventSerializationTest.java

* deprecate json in pb Any
* add encode/decode of json bytes

chore: Cleanup JsonSupport

---

akka-javasdk-tests/src/test/java/akkajavasdk/SdkIntegrationTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/ViewIntegrationTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/views/AllTheTypesKvEntity.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/views/AllTheTypesView.java
akka-javasdk-tests/src/test/resources/META-INF/akka-javasdk-components.conf
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewSchema.scala
akka-javasdk/src/test/java/akka/javasdk/testmodels/view/ViewTestModels.java
akka-javasdk/src/test/scala/akka/javasdk/impl/view/ViewDescriptorFactorySpec.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/view/ViewSchemaSpec.scala

Support for recursive types
Support for enums
End to end testcoverage of all types in row state (not covering indexing/filtering on each yet though)

chore: View updates

---

akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ConsumerImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/keyvalueentity/KeyValueEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/telemetry/Telemetry.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/timedaction/TimedActionImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewDescriptorFactory.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/timedaction/TimedActionImplSpec.scala

Refs https://github.com/lightbend/kalix-runtime/issues/3274
Jaeger screenshots:
Consumer (event-sourced-customer-registry sample)
Reliable timers cancelling pizza order after timeout

chore: Re-introduce trace spans for timed actions and consumers

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewDescriptorFactory.scala
project/Dependencies.scala

refers: https://github.com/lightbend/kalix-runtime/pull/3283

chore: adding class name to descriptors

---

docs/src/modules/java/pages/key-value-entities.adoc
docs/src/modules/java/pages/views.adoc
samples/view-store/README.md
samples/view-store/src/main/java/store/customer/api/CustomerEndpoint.java
samples/view-store/src/main/java/store/customer/application/CustomerEntity.java
samples/view-store/src/main/java/store/order/api/OrderEndpoint.java
samples/view-store/src/main/java/store/order/application/CreateOrder.java
samples/view-store/src/main/java/store/order/application/OrderEntity.java
samples/view-store/src/main/java/store/order/view/joined/CustomerOrder.java
samples/view-store/src/main/java/store/order/view/joined/JoinedCustomerOrdersView.java
samples/view-store/src/main/java/store/order/view/model/Customer.java
samples/view-store/src/main/java/store/order/view/model/Product.java
samples/view-store/src/main/java/store/order/view/nested/CustomerOrder.java
samples/view-store/src/main/java/store/order/view/nested/CustomerOrders.java
samples/view-store/src/main/java/store/order/view/nested/NestedCustomerOrders.java
samples/view-store/src/main/java/store/order/view/nested/NestedCustomerOrdersView.java
samples/view-store/src/main/java/store/order/view/structured/CustomerOrders.java
samples/view-store/src/main/java/store/order/view/structured/CustomerShipping.java
samples/view-store/src/main/java/store/order/view/structured/ProductOrder.java
samples/view-store/src/main/java/store/order/view/structured/ProductValue.java
samples/view-store/src/main/java/store/order/view/structured/StructuredCustomerOrders.java
samples/view-store/src/main/java/store/order/view/structured/StructuredCustomerOrdersView.java
samples/view-store/src/main/java/store/product/api/ProductEndpoint.java
samples/view-store/src/main/java/store/product/application/ProductEntity.java
samples/view-store/src/test/java/store/customer/api/CustomerEntityTest.java
samples/view-store/src/test/java/store/product/api/ProductEntityTest.java
samples/view-store/src/test/java/store/view/StoreViewIntegrationTest.java
samples/view-store/src/test/java/store/view/joined/JoinedCustomerOrdersViewIntegrationTest.java
samples/view-store/src/test/java/store/view/nested/NestedCustomerOrdersViewIntegrationTest.java
samples/view-store/src/test/java/store/view/structured/StructuredCustomerOrdersViewIntegrationTest.java

- package structure
- Endpoints instead of direct component calls
- removing remaining direct component calls docs

chore: aligning view store sample

---

docs/src/modules/operations/pages/projects/manage-project-access.adoc

Update permissions table to reflect that users that have Developer role assigned to them can delete services.
Closes: lightbend/kalix#12442

fix(docs): developer service deletion permissions

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewSchema.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/view/ViewDescriptorFactorySpec.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/view/ViewSchemaSpec.scala
project/Dependencies.scala

Downstream changes, waiting for merge+release of https://github.com/lightbend/kalix-runtime/pull/3307

chore: Update views to use new SPI type structure

---

docs/src/modules/java/pages/access-control.adoc
docs/src/modules/java/pages/event-sourced-entities.adoc
docs/src/modules/java/pages/http-endpoints.adoc
docs/src/modules/security/pages/acls.adoc

- improve discoverability of ACLs from endpoint docs
- avoid two pages with the exact same title (ACLs)

docs: cross references

---

docs/src/modules/java/pages/access-control.adoc

References
- https://github.com/lightbend/kalix/issues/12456

docs: explain backoffice for testing service

---

akka-javasdk/src/main/scala/akka/javasdk/impl/reflection/Reflect.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewDescriptorFactory.scala

after restarting the app with persistence enabled, I noticed:
```
Caused by: java.lang.IllegalStateException: Cannot decode [json.akka.io/customer.domain.CustomerRow] message type. Class mapping not found.
at akka.javasdk.impl.serialization.JsonSerializer.fromBytes(JsonSerializer.scala:97)
at akka.javasdk.impl.view.ViewDescriptorFactory$UpdateHandlerImpl.$anonfun$handle$2(ViewDescriptorFactory.scala:394)
at scala.Option.map(Option.scala:242)
at akka.javasdk.impl.view.ViewDescriptorFactory$UpdateHandlerImpl.$anonfun$handle$1(ViewDescriptorFactory.scala:394)
at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
at scala.concurrent.impl.Promise$Transformation.run$$$capture(Promise.scala:467)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala)
at --- Async.Stack.Trace …
```

fix: deserialize table updater row state

---

docs/src/modules/ROOT/pages/index.adoc
docs/src/modules/concepts/pages/development-process.adoc
docs/src/modules/concepts/pages/multi-region.adoc
docs/src/modules/concepts/pages/state-model.adoc
docs/src/modules/java/pages/access-control.adoc
docs/src/modules/java/pages/auth-with-jwts.adoc

Support should refer our support to customers not to features. I tried a different wording in some places.
Dropping some "coming soon" references.

docs: avoid using support for features; don't mention coming soon

---

docs/src/modules/operations/pages/services/deploy-service.adoc

There was no mention in the section to edit the service. 
Also a bit of rewording.

chore: adding edit service descriptor

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/test/scala/akka/javasdk/impl/AnySupportSpec.scala
build.sbt
project/Dependencies.scala

One test case breaking from runtime protobuf cleanup, then some unused protobuf module references.

chore: Drop some more protobuf refs

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/TestKit.java

There doesn't seem to be an `AkkaSdkTestkit` class.  Is this a vestige of an earlier name?

doc: Remove AkkaSdkTestkit from TestKit javadoc

---

docs/src/modules/reference/pages/cli/akka-cli/akka_services_list.adoc

Now that we are here we could add the three different `sync status` we have and maybe the `status` as well. Although I'm afraid to open a can of worms. For two reasons. One, doing something equivalent for each command would be some work and two, because all those changes would be more prone to get out of sync with the code base.

docs: adding sync status

---

docs/src/modules/java/pages/grpc-endpoints.adoc
docs/src/modules/java/pages/index.adoc
samples/doc-snippets/src/main/java/com/example/api/ExampleGrpcEndpointImpl.java
samples/doc-snippets/src/main/proto/com/example/example_grpc_endpoint.proto
samples/event-sourced-customer-registry/README.md
samples/event-sourced-customer-registry/src/main/java/customer/api/CustomerEndpoint.java
samples/event-sourced-customer-registry/src/main/java/customer/api/CustomerGrpcEndpointImpl.java
samples/event-sourced-customer-registry/src/main/proto/customer/api/customer_grpc_endpoint.proto

Basic docs and a more complete sample (no streaming there though)

doc: Sample and basic doc page

---

.github/workflows/ci.yml
akka-javasdk-maven/akka-javasdk-parent/pom.xml
docs/src/modules/java/pages/event-sourced-entities.adoc
docs/src/modules/java/pages/key-value-entities.adoc
docs/src/modules/reference/pages/release-notes.adoc
samples/event-sourced-counter-brokers/README.md
samples/transfer-workflow-compensation/README.md
samples/transfer-workflow/README.md

It seems `mvn integration-test` does not fail the build on test failure in all circumstances and `verify` is anyway the recommended way to run surefire integration tests according to their docs.

docs: Use mvn verify instead of mvn integration-test

---

.github/workflows/update-sdk-version.yml

References 
- Validator wasn't passing. See https://github.com/akka/akka-sdk/pull/184#issuecomment-2621136480
Inspiration from: https://github.com/orgs/community/discussions/26560#discussioncomment-3252340
- PR creating wasn't triggering https://github.com/akka/akka-sdk/actions/runs/13013470426
The filter `refs/tags/v` was wrong and not needed. We make this workflow depend on publish so checking if the trigger comes from a particular branch or tag it's unnecessary.

fix: creating the pr to update the samples when releasing

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/main/scala/akka/javasdk/impl/GrpcEndpointDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/grpc/GrpcClientProviderImpl.scala
project/Dependencies.scala
project/plugins.sbt

Depends on an Akka gRPC release and upstream bump in runtime before ready, but tested to work locally with Jaeger:

chore: Otel trace propagation through gRPC clients

---

docs/src/modules/operations/pages/observability-and-monitoring/observability-exports.adoc
docs/src/modules/reference/pages/descriptors/observability-descriptor.adoc

See https://github.com/lightbend/kalix/blob/3acc461ecfd9c2ffc3fdeb333316652d449c609a/operators/deployment/apis/kalix/v1alpha1/kalixobservability_types.go#L208

fix: reference to field in GoogleCloud spec

---

akka-javasdk/src/main/scala/akka/javasdk/impl/GrpcEndpointDescriptorFactory.scala

Noticed when testing grpc-web and got internal errors (MatchError from empty partial function).

fix: Actually specify an exception handler or gRPC endpoints

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestGrpcServiceImpl.java
akka-javasdk/src/main/java/akka/javasdk/annotations/Acl.java
akka-javasdk/src/main/scala/akka/javasdk/impl/AclDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/GrpcEndpointDescriptorFactory.scala
akka-javasdk/src/test/java/akka/javasdk/impl/http/TestEndpoints.java
akka-javasdk/src/test/java/akka/javasdk/testmodels/AclTestModels.java
akka-javasdk/src/test/scala/akka/javasdk/impl/HttpEndpointDescriptorFactorySpec.scala
samples/doc-snippets/src/main/java/com/example/acl/UserEndpoint.java

Close https://github.com/lightbend/kalix-runtime/issues/3407
I tinkered a bit with having 2 different methods on the annotation `httpDenyCode` and `grpcDenyCode` but then ended up with only `denyCode`. Let me know your thoughts.
Note that the `denyCode` was actually not being applied for HTTP endpoints (although we have it documented already). Thus, although this change might required source code changes for anyone using `denyCode` already (unlikely), it should not really impact anything.

feat: uniform deny codes for HTTP and gRPC endpoints

---

docs/src/modules/operations/pages/services/invoke-service.adoc

Noticed while working on verifying gRPC-web, the snippet with only CORS origin does not give you working CORS, it requires allowed methods as well, so include those in the snippet for easy copy pasta and understanding how it works.

docs: A working CLI CORS-enable snippet

---

docs/src/modules/java/pages/shopping-cart-quickstart.adoc

Fix numbering, formatting and missing spacing in shopping cart quickstart deployment instructions.
Closes: lightbend/kalix#12679

fix(docs): correct numbering in quickstart

---

.github/workflows/ci.yml
akka-javasdk-tests/src/test/java/akkajavasdk/GrpcEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestGrpcServiceImpl.java
akka-javasdk-tests/src/test/protobuf/akkajavasdk/test_grpc_service.proto
akka-javasdk/src/main/scala/akka/javasdk/impl/GrpcEndpointDescriptorFactory.scala

Noticed when writing docs for error responses. When throwing from user function with a GrpcStatusException or StatusRuntimeException, it would end up as Internal anyway on the client side without the message. This is because we are using the GrpcExceptionHandler from scaladsl (and not javadsl) and that one does not unwrap `CompletionException` exceptions as the one from java [does](https://github.com/akka/akka-grpc/blob/e51e4c685595bf13d91907d127e77c3710961cc8/runtime/src/main/scala/akka/grpc/javadsl/GrpcExceptionHandler.scala#L45).
I guess modifying the scala one to add that case does not make much sense, so composing the partial fucntion locally seemed OK.

fix: propagate custom gRPC status to client

---

project/Dependencies.scala

Next runtime release will be using scala 2.13.16 and the SDK must follow. 
This can be already merged though.

chore: bump scala version to 2.13.16

---

docs/src/modules/ROOT/pages/index.adoc

Replace the somewhat cryptic operations section with multi-* mentions.

docs: use multi-region, multi-cloud on index page

---

akka-javasdk-tests/src/test/java/akkajavasdk/GrpcEndpointTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestGrpcServiceImpl.java
akka-javasdk/src/main/scala/akka/javasdk/impl/GrpcEndpointDescriptorFactory.scala
docs/src/modules/java/pages/grpc-endpoints.adoc

Previous PR https://github.com/akka/akka-sdk/pull/205 fixed propagation of Grpc status exception but we still didn't log any details of the exception in dev mode neither did we provide a correlation id for the response.
With this PR, we let the exception bubble up to runtime to be taken care of there, where we put a correlation id and log all the details (if in dev mode).
... or should we duplicate the logic to handle different exceptions and log correlation id in the sdk side?

chore: improve propagation / conversion of exceptions

---

docs/src/modules/concepts/nav.adoc
docs/src/modules/concepts/pages/development-process.adoc
docs/src/modules/concepts/pages/grpc-vs-http-endpoints.adoc
docs/src/modules/java/pages/component-and-service-calls.adoc
docs/src/modules/java/pages/grpc-endpoints.adoc

Addressing Brent's [suggestion](https://github.com/lightbend/kalix-runtime/issues/3353#issuecomment-2660213149):
> I actually think doing the opposite of that would be best. I suggest a detailed doc page on where it's best to use HTTP vs gRPC Endpoints. This would be a great fit for the [Understanding section](https://doc.akka.io/concepts/index.html).

docs: understanding gRPC vs HTTP endpoints

---

docs/src/modules/java/pages/event-sourced-entities.adoc
docs/src/modules/java/pages/samples.adoc
docs/src/modules/java/pages/shopping-cart-quickstart.adoc

Changes the default location to obtain the shopping cart sample from the ZIP file to the Github repository.

linking shopping cart sample to github repo

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml

Without this change, the build will pass even when integration tests are failed:
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CartIntegrationTest>TestKitSupport.beforeAll:56 » Runtime Error while starting testkit
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.092 s
[INFO] Finished at: 2025-02-21T12:13:12+01:00
[INFO] ------------------------------------------------------------------------
```

chore: fail build on verify

---

Makefile
docs/antora-playbook-local.yml
docs/antora-playbook-prod.yml
docs/src/modules/operations/pages/observability-and-monitoring/view-logs.adoc
samples/shopping-cart-quickstart/src/main/java/shoppingcart/api/ShoppingCartEndpoint.java

This PR:
- restores snippet inadvertedly remove [here](https://github.com/akka/akka-sdk/pull/245)
- fixes 2 warns so that we can turn build failure on warn
- (this is arguable maybe... we can turn on and then see? if it turns out too annoying we can turn off again)

docs: restore missing snippet and remove all warnings

---

docs/src/modules/java/pages/http-endpoints.adoc
docs/src/modules/java/pages/views.adoc
samples/event-sourced-customer-registry/src/main/java/customer/application/CustomerByEmailView.java
samples/key-value-customer-registry/README.md
samples/key-value-customer-registry/src/main/java/customer/api/CustomerEndpoint.java
samples/key-value-customer-registry/src/main/java/customer/application/CustomersByCity.java
samples/key-value-customer-registry/src/main/java/customer/application/CustomersByName.java

References https://github.com/lightbend/kalix-runtime/issues/3077
Adds snippets for both regular stream result and for stream updates with a somewhat realistic query on customer city.

docs: Add a sample snippet to the view stream updates docs

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/TimedActionTestkit.java
akka-javasdk-testkit/src/main/scala/akka/javasdk/testkit/impl/AbstractTestKitContext.scala
akka-javasdk-testkit/src/main/scala/akka/javasdk/testkit/impl/TestKitEventSourcedEntityCommandContext.scala
akka-javasdk-testkit/src/main/scala/akka/javasdk/testkit/impl/TestKitEventSourcedEntityEventContext.scala
akka-javasdk/src/main/java/akka/javasdk/Context.java
akka-javasdk/src/main/java/akka/javasdk/OriginAwareContext.java
akka-javasdk/src/main/java/akka/javasdk/consumer/MessageContext.java
akka-javasdk/src/main/java/akka/javasdk/view/UpdateContext.java
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ConsumerImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/keyvalueentity/KeyValueEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/timedaction/TimedActionImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/timedaction/TimedActionImplSpec.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/view/ViewDescriptorFactorySpec.scala
docs/src/modules/java/pages/consuming-producing.adoc
docs/src/modules/java/pages/views.adoc

Draft since depending on https://github.com/lightbend/kalix-runtime/pull/3488

feat: make it possible to filter message by origin

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml

* if there are validations in the runtime that fails and terminates the ActorSystem, the jvm was not shutdown immediately
* cleanupDaemonThreads is by default true and that means that exec plugin will attempt to interrupt or join any daemon threads before shutting down
* setting this to false will simply shut down the VM when non-daemon thread execution completes
* see https://www.mojohaus.org/exec-maven-plugin/java-mojo.html#cleanupDaemonThreads

fix: Shutdown immediately if runtime fails

---

docs/src/modules/java/nav.adoc
docs/src/modules/java/pages/consuming-producing.adoc
docs/src/modules/java/pages/http-endpoints.adoc
docs/src/modules/java/pages/message-brokers.adoc
docs/src/modules/java/pages/running-locally.adoc
docs/src/modules/operations/nav.adoc
docs/src/modules/operations/pages/projects/broker-aws-msk.adoc
docs/src/modules/operations/pages/projects/message-brokers.adoc

Splitting out the currently identical pages
- Developing | Integrations | Configure message brokers
- Operating | Projects | Configure message brokers
https://doc.akka.io/operations/projects/message-brokers.html

docs: revise message brokers page structure

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml

References https://github.com/lightbend/kalix-runtime/issues/3570
Rather feels like this is something missing upstream, in the akka-grpc maven plugin. Leaving this as draft and investigating that.

chore: Mark Akka gRPC generated sources dir for IntelliJ autodetect

---

docs/src/modules/concepts/pages/multi-region.adoc

* the second paragraph became a block because of the indentation
see https://doc.akka.io/snapshots/akka-documentation/concepts/multi-region.html#_replicated_reads

docs: Format of definitions list

---

.github/workflows/pr-akka-samples.yml
akka-javasdk-maven/akka-javasdk-archetype/src/main/resources/archetype-resources/.gitignore
docs/release-issue-template.md
samples/choreography-saga-quickstart/.gitignore
samples/doc-snippets/.gitignore
samples/endpoint-jwt/.bundleignore
samples/event-sourced-counter-brokers/.bundleignore
samples/event-sourced-counter-brokers/.gitignore
samples/event-sourced-customer-registry-subscriber/.gitignore
samples/event-sourced-customer-registry/.gitignore
samples/key-value-counter/.gitignore
samples/key-value-customer-registry/.gitignore
samples/key-value-shopping-cart/.gitignore
samples/reliable-timers/.gitignore
samples/shopping-cart-quickstart/.gitignore
samples/spring-dependency-injection/.gitignore
samples/tracing/.gitignore
samples/transfer-workflow-compensation/.gitignore
samples/transfer-workflow/.bundleignore
samples/transfer-workflow/.gitignore
samples/view-store/.gitignore

Refs https://github.com/lightbend/kalix-runtime/issues/3542

build: Auto PR akka-samples

---

akka-javasdk/src/main/scala/akka/javasdk/impl/view/ViewDescriptorFactory.scala

We should be able to access `updateContext` from inside `emptyRow` for example, when we want to use the subject id as part of the view initial state.

fix: access updateContext from inside emptyRow

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/SerializationTestkit.java
akka-javasdk/src/main/java/akka/javasdk/JsonSupport.java
akka-javasdk/src/main/resources/reference.conf
akka-javasdk/src/main/scala/akka/javasdk/impl/HttpEndpointDescriptorFactory.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/Settings.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ConsumerImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ReflectiveConsumerRouter.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/http/JwtClaimsImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/keyvalueentity/KeyValueEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/serialization/JsonSerializer.scala
akka-javasdk/src/test/java/akka/javasdk/client/ComponentClientTest.java
akka-javasdk/src/test/scala/akka/javasdk/impl/serialization/JsonSerializationSpec.scala
project/Dependencies.scala

References https://github.com/lightbend/kalix-runtime/issues/3423
The object mapper available for customization through JsonSupport is now used, and only used, for HTTP endpoint and consumers when consuming from topics or producing to topics.
For internal JSON; stored in journal, used for component client, and in views, a separate, predictable/non-configurable object mapper is used.
Includes bump to runtime 1.4.3

feat: Customizable object mapper for endpoints

---

docs/src/modules/reference/pages/release-notes.adoc

Refs https://github.com/lightbend/kalix-runtime/releases/tag/v1.4.3

docs: update release notes for runtime 1.4.3

---

docs/src/modules/java/pages/workflows.adoc
samples/transfer-workflow/src/main/java/com/example/transfer/application/TransferWorkflow.java

See https://doc.akka.io/java/workflows.html#_workflow_definition 
the callout 1 being duplicated in combination with 5 don't quite make sense. 
Now: 
```
<1> Each step should have a unique name.
<2> Using the xref:component-and-service-calls.adoc#_component_client[ComponentClient], which is injected in the constructor.
<3> We instruct Akka to run a given asynchronous call to withdraw funds from a wallet.
<4> After successful withdrawal we return an `Effect` that will update the workflow state and move to the next step called "deposit." An input parameter for this step is a `Deposit` record.
<5> Another workflow step action to deposit funds to a given wallet.
<6> This time we return an effect that will stop workflow processing, by using the special `end` method.
<7> We collect all steps to …
```

chore: wrong callout number

---

project/Dependencies.scala

References
- [CVE-2024-12801](https://nvd.nist.gov/vuln/detail/CVE-2024-12801)

bump: logback 1.5.18 (was 1.5.12)

---

.github/kafka.yml
samples/event-sourced-counter-brokers/docker-compose.yml

Reverts akka/akka-sdk#353
References: https://github.com/lightbend/kalix-runtime/issues/3728
Sample test fails consistently in main with this, needs more investigation before we can bump.

Revert "bump: Confluent Kafka/Zookeeper 7.9.0 in Docker compose"

---

akka-javasdk-tests/src/test/java/akkajavasdk/SdkIntegrationTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/WorkflowWithTimer.java
akka-javasdk/src/main/java/akka/javasdk/timer/TimerScheduler.java
akka-javasdk/src/main/scala/akka/javasdk/impl/timer/TimerSchedulerImpl.scala
docs/src/modules/reference/pages/migration-guide.adoc
samples/choreography-saga-quickstart/src/main/java/user/registry/application/UniqueEmailConsumer.java
samples/reliable-timers/src/main/java/com/example/api/OrderEndpoint.java
samples/tracing/src/main/java/com/example/tracing/api/TracingEndpoint.java
samples/transfer-workflow-compensation/src/main/java/com/example/transfer/application/TransferWorkflow.java

@johanandren, here is the follow-up as discussed in #373
I have to introduce a `delete` method to pair with `create`. Also because the `cancel` is back to what it was and is now deprecated as well. 
I don't have strong opinions about it either. We can also close this PR if we believe it's not worth to introduce a deprecation cycle.

feat: create and delete methods for TimerScheduler

---

akka-javasdk-tests/src/test/java/akkajavasdk/WorkflowTest.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/TransferState.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/TransferWorkflow.java
akka-javasdk-tests/src/test/java/akkajavasdk/components/workflowentities/TransferWorkflowWithoutInputs.java
akka-javasdk/src/main/java/akka/javasdk/workflow/StepBuilder.java
akka-javasdk/src/main/java/akka/javasdk/workflow/Workflow.java
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/ReflectiveWorkflowRouter.scala

Adds support for passing a `Runnable` in a synchronous calls. 
When using a `Runnable` the corresponding `andThen` will accepts a `Supplier` only.

feat: support Runnable in Workflow calls

---

samples/ask-akka-agent/src/main/java/akka/ask/agent/application/AskAkkaAgent.java

We need to pass the `sessionId` to the chat memory so it can call the store with it. 
Otherwise, it will use `default`, but that won't work because we added the chat history using `sessionId`. 
Basically, when calling the LLM, we were not using the previous chat history.

chore: pass the sessionId to the memory store

---

docs/supplemental_ui/layouts/default.hbs

@beritou this adds the `default.hbs` file into the supplemental ui folder, and we add the `<chatlio-widget widgetid="b611b988-9e2b-4e36-566e-01a6d042121c"></chatlio-widget>` div to the site in preparation for a Chat widget that Nash is going to be testing out on the SDK docs.

add chatlio div for inserting widget

---

samples/ask-akka-agent/src/main/java/akka/ask/agent/api/UiEndpoint.java

Sorry for the PR overhead, but I spotted this typo en passant and couldn't let it go.

fix: typo in javadoc

---

docs/src/modules/java/pages/grpc-endpoints.adoc
docs/src/modules/java/pages/http-endpoints.adoc

Users had a hard time to discover the means to protect endpoints. Cross linking should help.

docs: cross link securing endpoints

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk/src/main/java/akka/javasdk/agent/AgentContext.java
akka-javasdk/src/main/java/akka/javasdk/client/AgentClient.java
akka-javasdk/src/main/java/akka/javasdk/client/AgentClientInSession.java
akka-javasdk/src/main/java/akka/javasdk/client/ComponentClient.java
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/client/AgentClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/client/ComponentClientImpl.scala
project/Dependencies.scala
samples/ask-akka-agent/pom.xml
samples/ask-akka-agent/src/main/java/akka/ask/agent/api/AskHttpEndpoint.java

* and another way of defining the sessionId in the agent component client
With the session we can correlate agents and conversations that participate in the same overall task. That is important for understanding what is going on and for eval. A standalone agent that is not having a conversation or collaboration should be extremely rare. If that is still needed it's just a matter of creating a new uuid for that call.
We intend to use the sessionId for connecting to our built in conversational memory, but that is not the reason why I want to make it mandatory. It's the above tracking that is most important.

feat: Mandatory sessionId

---

akka-javasdk/src/main/scala/akka/javasdk/impl/client/EntityClientImpl.scala

- fix a typo in a comment in EntityClientImpl.scala
- `sbt -v test` *(fails: sbt not found)*

Fix comment typo in EntityClientImpl

---

akka-javasdk/src/main/java/akka/javasdk/agent/PromptTemplate.java
akka-javasdk/src/main/java/akka/javasdk/agent/SessionMemoryEntity.java

I mentioned this issue before but didn't raise an issue and now I would rather fix it before we do a 1st release of the Agent things.
For the long run, I think we can now automatically scope the type names using the componentId as prefix but maybe that was not possible when we first implemented this.

chore: make collision of typename with user less likely

---

.github/workflows/pr-akka-samples.yml
.github/workflows/publish-sample-images.yml

https://github.com/akka/akka-sdk/pull/494 didn't work as intended when publishing 3.4.0-M1 because it was running from main and therefore the tag was 3.3.2. I think that was harmless, since that image from main should be fine.
This change will make it use the same branch as the original workflow.

build: Use original branch for workflow_run

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/agent/AgentIntegrationTest.java
akka-javasdk/src/main/java/akka/javasdk/agent/AgentRegistry.java
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentRegistryImpl.scala

* I had the wrong impression that Jackson couldn't format a generic collection

chore: Remove AgentInfoCollection

---

akka-javasdk/src/main/java/akka/javasdk/agent/SessionMessage.java
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala

Maps the tool request and responses from session memory back to runtime SPI format.
Draft because waiting for runtime pre-release.

fix: map tool request and responses to context msg

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/agent/SessionMemoryEntityTest.java
akka-javasdk/src/main/java/akka/javasdk/agent/SessionMemoryEntity.java
akka-javasdk/src/main/java/akka/javasdk/agent/SessionMessage.java
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala
samples/ask-akka-agent/src/main/java/akka/ask/agent/application/ConversationHistoryView.java
samples/doc-snippets/src/main/java/com/example/application/SessionMemoryConsumer.java
samples/doc-snippets/src/test/java/com/example/application/CompactionAgentIntegrationTest.java

This PR:
- uses Instant instead of long for timestamps in SessionMemory
- makes sure that the first message on the session memory is always a UserMessage.. important when we do auto truncation.
Refs:
- https://github.com/lightbend/kalix-runtime/issues/3831

chore: use Instant and remove orphans messages from memory

---

akka-javasdk-tests/src/test/java/akkajavasdk/components/grpc/TestGrpcServiceImpl.java

References https://github.com/lightbend/kalix-runtime/issues/3950

chore: Log more details if gRPC test not on virtual thread 

---

akka-javasdk-maven/akka-javasdk-parent/pom.xml
akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/TestKit.java
akka-javasdk-tests/src/test/java/akkajavasdk/HttpEndpointTest.java

Previous to this change, calls from the test or the service itself using the service name in Http client, gRPC client or MCP client would fail with a resolution error.
Depends on upstream SPI change in https://github.com/lightbend/kalix-runtime/pull/3987

chore: Self service resolution in integration tests

---

akka-javasdk-testkit/src/main/java/akka/javasdk/testkit/TestModelProvider.java
akka-javasdk-testkit/src/test/java/akka/javasdk/testkit/TestModelProviderTest.java

* to be able to change the responses, replacing a previous response

fix: TestModelProvider should match in opposite order

---

docs/src/modules/ROOT/partials/cli-install-short.adoc
docs/src/modules/getting-started/pages/author-your-first-service.adoc
docs/src/modules/getting-started/pages/planner-agent/activity.adoc
docs/src/modules/getting-started/pages/quick-install-cli.adoc
docs/src/modules/getting-started/pages/samples.adoc

Still not making it mandatory to use CLI first.

docs: Include akka code init in getting started

---

docs/src/modules/reference/pages/glossary.adoc

Fixes formatting of the glossary page.
- https://doc.akka.io/reference/glossary.html

docs: glossary format

---

akka-javasdk/src/main/java/akka/javasdk/eventsourcedentity/CommandContext.java
akka-javasdk/src/main/java/akka/javasdk/eventsourcedentity/EventContext.java
akka-javasdk/src/main/java/akka/javasdk/eventsourcedentity/EventSourcedEntity.java
akka-javasdk/src/main/java/akka/javasdk/eventsourcedentity/EventSourcedEntityContext.java
akka-javasdk/src/main/java/akka/javasdk/eventsourcedentity/package-info.java

See #735 
Mostly AI updates from the prompt:
```
Read the documentation from akka-context/java/event-sourced-entities.html.md
Improve the javadoc of the @eventsourcedentity classes based on the other documentation.
Don't include multi-line code snippets (<pre>) in JavaDoc aside from one single example in the EventSourcedEntity class javadoc.
```

docs: Improve JavaDoc of EventSourcedEntity

---

akka-javasdk/src/main/java/akka/javasdk/agent/McpToolCallExecutionException.java
akka-javasdk/src/main/java/akka/javasdk/annotations/mcp/McpEndpoint.java
akka-javasdk/src/main/java/akka/javasdk/annotations/mcp/McpPrompt.java
akka-javasdk/src/main/java/akka/javasdk/annotations/mcp/McpResource.java
akka-javasdk/src/main/java/akka/javasdk/annotations/mcp/McpTool.java
akka-javasdk/src/main/java/akka/javasdk/annotations/mcp/ToolAnnotation.java
akka-javasdk/src/main/java/akka/javasdk/mcp/AbstractMcpEndpoint.java
akka-javasdk/src/main/java/akka/javasdk/mcp/McpRequestContext.java

Mostly AI updates based on prompt:
```
Read the documentation from akka-context/java/mcp-endpoints.html.md
Improve the javadoc of the @mcp  classes based on the other documentation.
Don't include multi-line code snippets (<pre>) in JavaDoc aside from one single example in the AbstractMcpEndpoint class javadoc.
```

docs: Improve JavaDoc of McpEndpoint

---

docs/src/modules/ROOT/partials/concepts-intro.adoc
docs/src/modules/concepts/pages/architecture-model.adoc
docs/src/modules/concepts/pages/development-process.adoc
docs/src/modules/java/pages/components/index.adoc

Reorganize information to emphasize directory structure rather than abstract layers.
Move Akka component descriptions to conceptual introduction areas of docs.
Closes: lightbend/kalix#13763

docs: clarify project structure and components

---

samples/multi-agent/src/test/java/demo/multiagent/application/ActivityViewTest.java

This was failing when running integration tests in akka-samples. 
It's updated there now. We need this here in order to get this right in the next synch.

fix: use fake key when running integration tests

---

Makefile
docs/PRETTIER_IGNORE_REMOVAL.md
docs/bin/remove-prettier-ignore.sh
samples/doc-snippets/src/main/java/com/example/api/ExampleEndpoint.java
samples/doc-snippets/src/main/java/com/example/jwt/HelloJwtEndpoint.java
samples/doc-snippets/src/test/java/com/example/MyIntegrationTest.java
samples/endpoint-jwt/src/main/java/hellojwt/api/HelloJwtEndpoint.java
samples/helloworld-agent/src/main/java/com/example/application/HelloWorldAgent.java
samples/reliable-timers/src/main/java/com/example/application/OrderEntity.java
samples/shopping-cart-quickstart/src/main/java/shoppingcart/application/ShoppingCartEntity.java
samples/shopping-cart-quickstart/src/test/java/shoppingcart/application/ShoppingCartTest.java
samples/spring-dependency-injection/src/main/java/com/example/CounterSetup.java

Using comment with `prettier-ignore` to disable formatting in some specific situations. 
And added a script to remove those lines from the generated site.

chore: add prettier-ignore for format control

---

docs/src/modules/java/nav.adoc
docs/src/modules/java/pages/model-provider-details.adoc
docs/src/modules/java/pages/setup-and-configuration/index.adoc
docs/styles/config/vocabularies/Akka/accept.txt

This makes a significant improvement to the page, making it easier for developers to scan and find the configuration they're looking for and moves the "noise" of the raw configuration text to their own sections at the bottom.
This page also didn't have a position on the left nav, so I've added it to the Setup and Configuration section.

making the AI model provider config page more dev friendly

---

docs/src/modules/concepts/pages/concepts.adoc

Relocate component interoperability section to follow agentic runtime explanation.
Closes: lightbend/kalix#13823

chore(docs): move component interoperability

---

docs/src/modules/ROOT/partials/create-the-empty-project.adoc
docs/src/modules/getting-started/pages/ask-akka-agent/the-agent.adoc
docs/src/modules/getting-started/pages/planner-agent/activity.adoc
docs/src/modules/getting-started/pages/shopping-cart/build-and-deploy-shopping-cart.adoc

Replace outdated Akka CLI download steps with reusable project creation partial.
Ensure consistency across samples and align with initial getting started flow.
Closes: #837

fix(docs): shopping-cart sample setup instructions

---

docs/src/modules/getting-started/pages/author-your-first-service.adoc

It became mandatory in https://github.com/akka/akka-sdk/pull/764

chore: Mandatory OpenAI key

---

akka-javasdk/src/main/scala/akka/javasdk/impl/serialization/JsonSerializer.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/serialization/JsonSerializationSpec.scala

Besides the optimization, it also fixes this issue:
```
java.lang.IllegalStateException: Cannot decode [json.akka.io/akka.Done$] message type. Class mapping not found.
at akka.javasdk.impl.serialization.JsonSerializer.fromBytes(JsonSerializer.scala:215)
at akka.javasdk.impl.workflow.ReflectiveWorkflowRouter.decodeInput(ReflectiveWorkflowRouter.scala:73)
at akka.javasdk.impl.workflow.ReflectiveWorkflowRouter.applyTransitionFunc$1(ReflectiveWorkflowRouter.scala:194)
at akka.javasdk.impl.workflow.ReflectiveWorkflowRouter.getNextStep(ReflectiveWorkflowRouter.scala:204)
at akka.javasdk.impl.workflow.WorkflowImpl.liftedTree1$1(WorkflowImpl.scala:301)
at akka.javasdk.impl.workflow.WorkflowImpl.transition(WorkflowImpl.scala:299)
at kalix.runtime.EmbeddedSdkDispatch$$anon$4.$anonfun$transition$1(Em …
```

fix: done deserialization

---

.github/workflows/documentation.yml
samples/README.md

Trigger doc generation job when files under `samples` are modified. 
In case the tagging or callouts get broken, CI will detect it.

chore: run doc gen if samples are modified

---

akka-javasdk/src/main/scala/akka/javasdk/impl/MetadataImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/client/ComponentClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ConsumerImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/eventsourcedentity/EventSourcedEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/grpc/GrpcClientProviderImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/http/HttpClientProviderImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/keyvalueentity/KeyValueEntityImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/telemetry/SpanTracingImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/telemetry/Telemetry.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/timedaction/TimedActionImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/workflow/WorkflowImpl.scala
akka-javasdk/src/test/java/akka/javasdk/client/ComponentClientTest.java

We need the whole trace context for debug tracing (including trace state). Use the telemetry context rather than just the span, and start supporting full context propagation. Can then also support other distributed contexts, like w3c baggage propagation. The telemetry context is already passed for some SPI contexts. `FIXME(tracing)` comments added for other parts that will be updated next.

fix: full telemetry context propagation

---

akka-javasdk/src/main/java/akka/javasdk/workflow/Workflow.java
akka-javasdk/src/main/scala/akka/javasdk/impl/ErrorHandling.scala
project/Dependencies.scala

Looked like this:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at akka.javasdk.workflow.Workflow$StepMethod.invoke(Workflow.java:930)
at akka.javasdk.impl.workflow.ReflectiveWorkflowRouter.$anonfun$handleStep$7(ReflectiveWorkflowRouter.scala:204)
at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: java.lang.reflect.InvocationTargetException: null
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor …
```

fix: InvocationTargetException causing confusion of workflow logs

---

akka-javasdk-testkit/src/main/scala/akka/javasdk/testkit/impl/EventingTestKitImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/MetadataImpl.scala

A change to test eventing in latest runtime meant that metadata only contained the cloud event attributes, and not the `Content-Type` header. The metadata on the SDK side always uses `Content-Type` for `ce-datacontenttype`. We probably want to have a better separation between cloud events and their encodings that use `Content-Type`. Test eventing in runtime can be adjusted to add the `Content-Type` entry again, but also add a fallback in the metadata implementation here so that things are more robust.

fix: content-type fallback for cloud events in metadata

---

.github/workflows/pr-akka-samples.yml
docs/release-issue-template.md

* since it's randomly not picking up the right tag or content
* harden the script to use unique branches and not fail when no changes

build: Run sync samples manually after release

---

akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/agent/AgentImpl.scala

We weren't connecting traces for internal component calls to the session memory and prompt template entities. So these were all recorded as separate traces.
---
By setting the telemetry context on the component clients, we now get a single trace:
---
And the entity interactions within the command spans:
---
If we've subscribed to the session memory events, then consumer trace spans will be connected from there.

fix: context propagation from agents to memory and template entities

---

akka-javasdk/src/main/scala/akka/javasdk/impl/SdkRunner.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/client/ComponentClientImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ConsumerImpl.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/consumer/ReflectiveConsumerRouter.scala
akka-javasdk/src/main/scala/akka/javasdk/impl/timedaction/TimedActionImpl.scala
akka-javasdk/src/test/scala/akka/javasdk/impl/timedaction/TimedActionImplSpec.scala

Context propagation from consumer to components was working, by setting a volatile var directly, but no telemetry context for other clients. Timed actions didn't have any context propagation. Fix both using the context injection approach used for other components, and we now get connected traces.

fix: context propagation from consumer and timed action
